routes/web.php
<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('logout', function(){
	auth()->logout();

	return redirect()->to('/');
})->name('logout');

Route::post('/loginWithId', function(){
	Auth::loginUsingId(request()->id);
	return redirect()->to('/');
});

Auth::routes();
Route::get('/', 'HomeController@index')->name('index');
Route::get('grid', 'ActiveCellController@ajax');

#pusher
Route::middleware('auth')->group(function(){
	Route::get('messages', 'MessageController@index');
	Route::get('messages/{user}', 'MessageController@create');
	Route::post('messages/{user}', 'MessageController@store');
	Route::post('comments/{post}', 'CommentController@store');
	Route::post('likes/{comment}/comments', 'LikeController@comment');
	Route::post('likes/{post}/posts', 'LikeController@post')->name('likes.posts');

	Route::get('notifications/read-all', function(){
		auth()->user()->unreadNotifications->markAsRead();
		return back();
	});

	Route::resource('posts', 'PostController', ['parameters' => 'post']);
	Route::resource('users', 'UserController', ['parameters' => 'user']);
	Route::post('posts/{post}/chats', 'ChatController@store')->name('posts.chat');

});

require __DIR__ . '/others.php';

app/Post.php
<?php

namespace App;

use App\Notifications\UserComment;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Notification;

class Post extends Model
{
	public function category()
	{
		return $this->belongsTo(Category::class);
	}

	public function user()
	{
		return $this->belongsTo(User::class);
	}

    public function comments()
    {
        return $this->hasMany(Comment::class)->orderByDesc('created_at');
    }

    public function hands()
    {
    	return $this->morphMany(Hand::class, 'handable');
    }

    public function chats()
    {
    	return $this->hasMany(Chat::class);
    }

    public function notifyPost($post)
    {
        Notification::send($this->user, new UserComment($post, auth()->user()));
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Chat;
use App\Hand;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redis;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = auth()->user()->posts()->with('category')->get();

        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = Hand::getClass('App\Comment')
                    ->getUser()
                    ->pluck('handable_id')
                    ->toArray();

        $post = Post::with('comments.user')
                ->with(['comments' => function($q){
                        $q->withCount('hands');
                }])->where('id', $id)->firstOrFail();

        $chats = Chat::select('body', 'created_at', 'user_id')
                ->with('user')
                ->where('post_id', $post->id)
                ->orderBy('created_at')
                ->get();

        // $visits = Redis::incr("post_visits_{$post->id}");
        $visits = 1;

        return view('posts.show', compact('user', 'post', 'chats', 'visits'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->comments()->delete();

        $post->chats()->delete();

        $post->hands()->delete();

        $post->delete();

        return redirect()->to('posts');
    }
}

resources/views/posts/chat.blade.php
<div class="panel panel-primary">
	<div class="panel-heading">
		Chat en grupo
	</div>

	<div class="panel-body">
		<ul id="post-chat" style="height: 200px; list-style: none; overflow-y: scroll;">
            @foreach ($chats as $chat)
                <li>
                    <strong>{{ $chat->user->name }}</strong>
                    {{ $chat->body }}
                </li>
            @endforeach
        </ul>
	</div>

    <div class="panel-footer">
        <form method="POST" action="{{ route('posts.chat', [$post->id]) }}" id="post-form-chat">
            {{ csrf_field() }}
            <div class="input-group">
                <input type="text" name="body" id="body" autocomplete="off" class="form-control input-sm">
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-default btn-sm">Enviar</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        Usuarios en este grupo
    </div>

    <div class="panel-body">
        <ul id="post-users-online" style="height: 150px; list-style: none; overflow-y: scroll;">
        </ul>
    </div>
</div>

resources/views/posts/comments.blade.php
@foreach ($post->comments as $comment)
	<div class="media" id="{{ $comment->id }}">
	    <a class="pull-left" href="{{ url('users', [$comment->user->id]) }}">
	        <img class="media-object" src="http://placehold.it/64x64" alt="">
	    </a>

		<div class="media-body">
		    <h4 class="media-heading">
		    	{{ $comment->user->name }}
		        <small>
		        	{{ $comment->created_at->diffForHumans() }}
		        </small>
		    </h4>

			<span class="pull-right like-count">{{ $comment->hands_count > 0 ?: '' }}</span>

		    {{ $comment->body }}

		    <p>
		    	<a href="#" class="btn-like" data-id="{{ $comment->id }}" title="Me gusta">
		    		{{ in_array($comment->id, $user) ? 'Te gusta' : 'Me gusta' }}
		    	</a>
		    </p>
		</div>
	</div>
@endforeach

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="page-header">
          <h1>Tus Posts <small>({{ $posts->count() }})</small></h1>
        </div>
        <div class="col-md-10">
            @foreach ($posts as $post)
                <div class="well" style="margin-bottom: 10px">
                    <a href="{{ url('posts', [$post->id]) }}">
                        {{ $post->body }}
                    </a>
                    <div class="pull-right">
                        {{ $post->category->name }}
                        <i class="fa fa-clock-o"></i> {{ $post->created_at->diffForHumans() }}
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>

@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@push('css')
<script type="text/javascript">
	window.App = @json(['postId' => $post->id])
</script>
@endpush

@section('content')

<div class="container">
    <div class="row">
		<div class="col-lg-8">
		    <h1>
		    	{{ $post->body }}
		    </h1>
		    <p class="lead">
		        Por <a href="{{ route('users.show', [$post->user->id]) }}">
		        		{{ $post->user->name }}
		        	</a>

		    </p>

			<small>
				{{ $visits }} {{ str_plural('visita', $visits) }}
			</small>

		    <hr>

		    <p>
		    	<span class="glyphicon glyphicon-time"></span> Posted on {{ $post->created_at->diffForHumans() }}
		    	@if ($post->user_id === auth()->id())
		    		<form action="{{ url('posts', $post->id) }}" method="POST">
		    			{{ csrf_field() }}
		    			{{ method_field('DELETE') }}
		    			<button type="submit" class="btn btn-danger">Borrar</button>
		    		</form>
		    	@endif
		    </p>

			<form class="pull-right" method="POST" action="{{ route('likes.posts', [$post->id]) }}">
				{{ csrf_field() }}
				@auth
					@if (auth()->user()->hands()->getClass('App\Post')->where('handable_id', $post->id)
							->exists())
						<button type="submit" disabled class="btn btn-default btn-sm">Guardado</button>
					@else
						<button type="submit" class="btn btn-primary btn-sm">Guardar</button>
					@endif
				@endauth
			</form>

		    <hr>

		    <img class="img-responsive" src="http://placehold.it/900x300" alt="">

		    <hr>

		    <p class="lead">
		    	{{ $post->body }}
		    </p>

		    <hr>

		    <div class="well">
		        <h4>Leave a Comment:</h4>
		        <form role="form" method="POST" action="{{ url('comments', [$post->id]) }}">
		        	{{ csrf_field() }}
		            <div class="form-group">
		                <textarea class="form-control" rows="3" name="body"></textarea>
		            </div>
		            <button type="submit" class="btn btn-primary">Submit</button>
		        </form>
		    </div>

		    <hr>

		    @include('posts.comments')
		</div>
		<div class="col-lg-4">
			@include('posts.chat')
		</div>
    </div>
</div>

<hr>

@endsection

@push('js')
<script src="{!! asset('js/notifications.js') !!}"></script>
@endpush